name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17
          distribution: liberica
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: build --stacktrace -PrunDetekt -x test

  detekt:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17
          distribution: liberica

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: ktlintMainSourceSetCheck --stacktrace

      - uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: ktlintKotlinScriptCheck --stacktrace

      - uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: ktlintTestSourceSetCheck --stacktrace
          